baseURL = 'https://example.org/'
locale = 'en-us'
title = 'My New Hugo Project'

[params]
  author = 'Benjamin Crews'
  description = 'The personal blog of Benjamin Crews.'
  disable_theme_toggle = false
  disable_stay_uptodate = true

[module]
  [[module.imports]]
    path = 'tailbliss'
    [[module.imports.mounts]]
      source = 'archetypes'
      target = 'archetypes'
    [[module.imports.mounts]]
      source = 'assets'
      target = 'assets'
    [[module.imports.mounts]]
      source = 'data'
      target = 'data'
    [[module.imports.mounts]]
      source = 'i18n'
      target = 'i18n'
    [[module.imports.mounts]]
      source = 'layouts'
      target = 'layouts'
    [[module.imports.mounts]]
      source = 'static'
      target = 'static'

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    identifier = 'posts'
    name = 'Posts'
    url = '/posts/'
    weight = 20

[caches]
  [caches.images]
    dir = ':cacheDir/images'